### ISSUE TITLE
StatusCallback not working

### ISSUE THREAD

**Issue by absarmushtaq-unifonic** [somleng/twilreapi#743]
I am using a Curl request to initiate an outbound call and its working fine. The issue is that whatever URL I give in the `StatusCallback` parameter, I receive no response there. I have tried online mock API sites like requestcatcher.com but no success. 
Can you guide that what can be the problem? 
`curl -X POST http://localhost:3000/api/2010-04-01/Accounts/$ACCOUNT_SID/Calls.json \
    -d "Method=GET" \
    -d "Url=http://demo.twilio.com/docs/voice.xml" \
    -d "To=$Recipient_Number" \
    -d "From=$Mobile_Number" \
    -d "StatusCallback=https://$subdomain.requestcatcher.com/$endpoint" \
    -u '$ACCOUNT_SID:$AUTH_TOKEN'`

**Comment by dwilkie** [comment]
We’re in the middle of a rewrite #652, so if your using this branch this notification is send when the Call Data Record is received. It’s sent in a background job here’s the code which initiates the status callback notification. https://github.com/somleng/twilreapi/blob/upgrade_infrastructure/app/jobs/process_cdr_job.rb

If your on the develop branch, then it’s triggered when the phone call transitions to completed. This happens also when the Call Data Record is received.

In both cases you will need to setup FreeSWICH to send the Call Data Record in order to trigger the status callback notification

**Comment by absarmushtaq-unifonic** [comment]
@dwilkie Thanks for your response. I am using the default branch i.e, `develop`. FreeSWITCH is configured already and I can receive the outbound call as well. I didn't get your point properly about 

> In both cases you will need to setup FreeSWICH to send the Call Data Record in order to trigger the status callback notification

What setup do I need to trigger the status callback notification ?

**Comment by dwilkie** [comment]
Hello, we just finished a rewrite of Somleng. Follow the getting started guide to get it up and running on your local machine.

https://github.com/somleng/somleng-project/blob/master/docs/GETTING_STARTED.md
